//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRInputs : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 joystick_position
        {
            get
            {
                return SteamVR_Actions.vRInputs_joystick_position;
            }
        }
        
        public virtual SteamVR_Action_Single trigger_pull
        {
            get
            {
                return SteamVR_Actions.vRInputs_trigger_pull;
            }
        }
        
        public virtual SteamVR_Action_Single grip_pull
        {
            get
            {
                return SteamVR_Actions.vRInputs_grip_pull;
            }
        }
        
        public virtual SteamVR_Action_Boolean primary_button
        {
            get
            {
                return SteamVR_Actions.vRInputs_primary_button;
            }
        }
        
        public virtual SteamVR_Action_Boolean secondary_button
        {
            get
            {
                return SteamVR_Actions.vRInputs_secondary_button;
            }
        }
    }
}
